version: "3.8" 
services:
  db: 
    image: postgres:12 
    volumes: 
      - type: volume
        source: k1ngSochialMedia
        target: /var/lib/postgresql/data
    ports:
      - "2727:5432"
    environment: 
      POSTGRES_USER: king
      POSTGRES_DB: kingSochialMedia
      POSTGRES_PASSWORD: king

volumes:
  k1ngSochialMedia:
    driver: local